### ISSUE TITLE
CIS_front : problème lors de `npm run build`

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/CIS-front#287]
en suivant les instructions du Readme : 
- `git pull origin master`
- `cd /cis/app/frontend` --> ok
- `npm install` --> ok (mais aussi + `npm audit fix --force` pour régler les problèmes de vulnérabilité)
- `npm run build` --> erreur

**Comment by JulienParis** [comment]
```
♲  jpy@JPyPro ~/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
$ npm run build

> cis-front@1.0.0 build /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> npm-run-all --parallel build:*


> cis-front@1.0.0 build:css /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> node-sass --omit-source-map-url styles/main.scss ../static/build/bundle.css


> cis-front@1.0.0 build:js /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> browserify ./scripts/main.js -o ../static/build/bundle.js

module.js:545
    throw err;
    ^

Error: Cannot find module './args'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/.bin/browserify:6:9)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cis-front@1.0.0 build:js: `browserify ./scripts/main.js -o ../static/build/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cis-front@1.0.0 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpy/.npm/_logs/2019-02-12T14_32_00_633Z-debug.log
ERROR: "build:js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cis-front@1.0.0 build: `npm-run-all --parallel build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cis-front@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpy/.npm/_logs/2019-02-12T14_32_00_719Z-debug.log 
```

**Comment by JulienParis** [comment]
@DavidBruant qu'est-ce que tu en penses ?

**Comment by DavidBruant** [comment]
Est-ce que tu peux réessayer sans `npm audit fix --force` voir ce que ça donne ?

**Comment by JulienParis** [comment]
je viens de tester une autre méthode en suivant cette méthode [stackoverflow](https://stackoverflow.com/questions/28929657/error-cannot-find-module-args) : 
1. delete node_modules
1. npm install

resultats : 
```
🌱♲  jpy@JPyPro ~/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
$ npm install

> fsevents@1.2.4 install /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> node-sass@4.11.0 install /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/jpy/.npm/node-sass/4.11.0/darwin-x64-59_binding.node

> node-sass@4.11.0 postinstall /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
npm WARN cis-front@1.0.0 No description
npm WARN cis-front@1.0.0 No repository field.

added 684 packages from 505 contributors and audited 4315 packages in 26.979s
found 0 vulnerabilities

🌱♲  jpy@JPyPro ~/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
$ npm run build

> cis-front@1.0.0 build /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> npm-run-all --parallel build:*


> cis-front@1.0.0 build:css /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> node-sass --omit-source-map-url styles/main.scss ../static/build/bundle.css


> cis-front@1.0.0 build:js /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/frontend
> browserify ./scripts/main.js -o ../static/build/bundle.js

Rendering Complete, saving .css file...
Wrote CSS to /Users/jpy/Dropbox/_FLASK/_CIS/_POC_EIG/CIS_front/cis/app/static/build/bundle.css
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

**Comment by JulienParis** [comment]
ok c résolu.. je v ajouter ça au readme

**Comment by JulienParis** [comment]
@DavidBruant par contre ces warnings `You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.` c quoi exactement ?

**Comment by DavidBruant** [comment]
> @DavidBruant par contre ces warnings `You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.` c quoi exactement ? ya moyen de rendre ça plus clean ?

#46
