### ISSUE TITLE
Pas de chargement des pages Vue.js

### ISSUE THREAD

**Issue by CBalsier** [entrepreneur-interet-general/CIS-front#300]
Pas de chargement des pages Vue.js (`/recherche`, `/recherche/carte`, `/project/id`)

- Code : branche `master` fraîchement clonée, packets installés comme prévu (`pip`/`npm`)
- Système :
        - VM Ubuntu : Linux 1.18.0-15-generic, Ubuntu 18.04
        - Hôte : Windows 7 installation CGET
        - Navigateurs : Firefox 65 (12 février 2019), Chromium 71
        - testé sur réseau CGET et téléphone
- Symptômes :
        - les éléments de la page (`bundle.js`, `bundle.css`, `spa.html`) sont atteints (réponse 200)
        - la page reste vide et blanche (cf. capture d’écran) : rien dans le `<body>` (même pas le `<div id="vue-content">`)
        - trace python d’une requête :
```
127.0.0.1 - - [27/Feb/2019 17:29:20] "GET /recherche HTTP/1.1" 200 -
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + -
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST ///
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + -
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST ///
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + -
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - 
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - 
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - 
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/json/CHOICES_FILTERS_TAGS.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/json/CATEGORIES_CIS_DICT_FLAT.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/json/NORMALIZATION_TAGS_SOURCES_CIS_DICT.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/json/CHOICES_FILTERS_GEOLOC.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/json/NOMENCLATURE_CIS_DICT.js HTTP/1.1" 200 -

+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - 
D ::: log_cis 19-02-27 17:29:21 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/build/bundle.css HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2019 17:29:21] "GET /static/build/bundle.js?v3 HTTP/1.1" 200 -

+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - 
D ::: log_cis 19-02-27 17:29:23 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST /// 
D ::: log_cis 19-02-27 17:29:23 ::: views:114 -in- home() :::  entering new home page
D ::: log_cis 19-02-27 17:29:23 ::: model_user:23 -in- __init__() :::  creating AnonymousUser
127.0.0.1 - - [27/Feb/2019 17:29:23] "GET / HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/home/cbalsier/CIS-front-master/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/cbalsier/CIS-front-master/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/cbalsier/CIS-front-master/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

+ - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + - + -
D ::: log_cis 19-02-27 17:29:23 ::: __init__:121 -in- before_request() :::  /// NEW REQUEST ///
E ::: log_cis 19-02-27 17:29:23 ::: views:76 -in- error404() :::  error - 404 : 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually   please check your spelling and try again.
D ::: log_cis 19-02-27 17:29:23 ::: model_user:23 -in- __init__() :::  creating AnonymousUser
127.0.0.1 - - [27/Feb/2019 17:29:23] "GET /favicon.ico HTTP/1.1" 404 -

```

![screenshot from 2019-02-27 18-06-59](https://user-images.githubusercontent.com/11838444/53508727-9cc51300-3aba-11e9-86d7-f219d6f2c1ed.png)
- + sur réseau CGET + Chrome, `cis-openscraper.com` n’est pas joignable (pas de problème sous Firefox, ni sur le tel)

**Comment by JulienParis** [comment]
à noter qu'un run de l'application après un pull simple du master sur un système sans VM particulière de type apple (ma machine perso) ou ubuntu (machine de David ou le serveur de prod) fonctionne sans problème... 

pe vérifier que le header envoyé par le client lorsqu'il faut aller requêter (fetch) les données sur cis-openscraper arrive à "sortir" de la VM et/ou n'est pas bloqué par les pare-feux du wifi CGET...

**Comment by CBalsier** [comment]
Après cet aprèm : 
- les components `SearchMapScreen` et `SearchListScreen` sont bien rendus si appelés en dur dans `main.js`
- par contre, si chargés avec `Vue.component( 'router-view')`, la page reste blanche
-> problème de `router-view` ? par exemple mise à jour ou nouveau fonctionnement ?

Versions utilisées : 
- `npm view router-view` done 1.1.7
-  Vue 2.6.8.

**Comment by CBalsier** [comment]
Si le problème se représente : 
- vérifier avec `npm view vue-router version` la version de `vue-router` installée
- désinstaller avec `npm uninstall vue-router`
- réinstaller avec `npm install vue-router@3.0.1` (version en prod et au fonctionnement vérifié)
